// src/Card.tsx
interface ICardProps {
    value: string;
    icon: string;
    featureName: string;
    unit: string;
    color: string;
}
const Card = (props: ICardProps) => {

    const classCard = "card text-white m-3 w-2 " + props.color;
    const iconClass = "fa-4x " + props.icon;
    return (
        <div className={classCard}>
            <h3 className="text-center mt-2 w-700px">{props.featureName}</h3>
            <div className="d-flex justify-content-around align-items-center">
            <i className={iconClass}></i>
            <p className="text-white text-end"><span className="display-3">{props.value}</span>{props.unit}</p>
        </div>
    </div>
    )
}
export default Card;

// src/app/card/card.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './card.component.html',
  styleUrl: './card.component.scss'
})
export class CardComponent {

  @Input() featureName: string = "Nao definido";
  @Input() color: string = "bg-info";
  @Input() icon: string = "";
  @Input() value: string = "";
  @Input() unit: string = "bpm";

}

<div class="card text-white {{color}} mt-3 w-2">
    <h3 class="text-center mt-2 w-700px">{{ featureName }}</h3>
    <div class="d-flex justify-content-around align-items-center">
        <i class="{{icon}} fa-4x"></i>
        <p class="text-white text-end"><span class="display-3">{{ value }}</span>{{unit}}</p>
    </div>
</div>
